variables:
  CI: true

trigger:
  paths:
    include:
    - "+hdf5nc/*"
    - azure-pipelines.yml

pool:
  vmImage: ubuntu-latest
steps:
  - task: InstallMATLAB@0

  - task: RunMATLABCommand@0
    inputs:
      command: 'disp(version), TestAll'

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: test-results/results.xml

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: code-coverage/coverage.xml
